### ISSUE TITLE
bash error

### ISSUE THREAD

**Issue by gatemezing** [ghxiao/owl-toolkit#2]
Hi, just downloaded and followed the README file, but on my MAc, I have the following error: "-bash: owl-metrics: command not found". Did I miss something? TIA.

**Comment by ghxiao** [comment]
Hi, 

Try first `cd` to the directory of owl-toolkit, and run `./owl-metrics`. The part of `./` is mandatory since `owl-metrics` is not in the `$PATH` .

**Comment by gatemezing** [comment]
Thanks, but still have an issue. It says now that can not find the main class org.ghxiao.owltoolkit.OWLMetrics
![owl-toolkit](https://cloud.githubusercontent.com/assets/922883/8499334/211215d6-2192-11e5-833c-c465f5107b39.png)
Note: I just downloaded the latest binary in .Zip.
Btw, you can update the README file with the info you provided earlier. HTH

**Comment by ghxiao** [comment]
I only tested the scripts on Mac OS X and Linux.
It seems to be a problem specific to the platform on cygwin. 

Could you try the following command to invoke the jar directly:

```
java -cp owl-toolkit.jar org.ghxiao.owltoolkit.OWLMetrics your_ontology_file.owl
```
